"""
Fallback stock data for when market APIs are unavailable
"""


def get_fallback_stock_data():
    """
    Get pre-defined stock data for when yfinance is unavailable
    This is based on historical data and should only be used for demos
    """
    return [
        {
            'ticker': 'AAPL',
            'name': 'Apple Inc.',
            'sector': 'Technology',
            'industry': 'Consumer Electronics',
            'current_price': 175.50,
            'market_cap': 2750000000000,
            'pe_ratio': 28.5,
            'dividend_yield': 0.0050,
            'beta': 1.25,
            '52_week_high': 198.23,
            '52_week_low': 124.17,
            'avg_volume': 55000000,
            'description': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories...'
        },
        {
            'ticker': 'MSFT',
            'name': 'Microsoft Corporation',
            'sector': 'Technology',
            'industry': 'Software',
            'current_price': 380.00,
            'market_cap': 2830000000000,
            'pe_ratio': 34.2,
            'dividend_yield': 0.0078,
            'beta': 0.95,
            '52_week_high': 420.82,
            '52_week_low': 245.22,
            'avg_volume': 25000000,
            'description': 'Microsoft Corporation develops and supports software, services, devices, and solutions worldwide...'
        },
        {
            'ticker': 'JNJ',
            'name': 'Johnson & Johnson',
            'sector': 'Healthcare',
            'industry': 'Drug Manufacturers',
            'current_price': 156.75,
            'market_cap': 412000000000,
            'pe_ratio': 15.8,
            'dividend_yield': 0.0295,
            'beta': 0.55,
            '52_week_high': 169.23,
            '52_week_low': 143.13,
            'avg_volume': 8000000,
            'description': 'Johnson & Johnson researches, develops, manufactures, and sells various products in the healthcare field...'
        },
        {
            'ticker': 'JPM',
            'name': 'JPMorgan Chase & Co.',
            'sector': 'Financial Services',
            'industry': 'Banks',
            'current_price': 162.00,
            'market_cap': 468000000000,
            'pe_ratio': 11.2,
            'dividend_yield': 0.0235,
            'beta': 1.18,
            '52_week_high': 172.05,
            '52_week_low': 123.89,
            'avg_volume': 12000000,
            'description': 'JPMorgan Chase & Co. operates as a financial services company worldwide...'
        },
        {
            'ticker': 'WMT',
            'name': 'Walmart Inc.',
            'sector': 'Consumer Defensive',
            'industry': 'Discount Stores',
            'current_price': 165.50,
            'market_cap': 440000000000,
            'pe_ratio': 30.5,
            'dividend_yield': 0.0140,
            'beta': 0.52,
            '52_week_high': 169.94,
            '52_week_low': 134.57,
            'avg_volume': 8500000,
            'description': 'Walmart Inc. engages in the operation of retail, wholesale, and other units worldwide...'
        },
        {
            'ticker': 'PG',
            'name': 'Procter & Gamble Company',
            'sector': 'Consumer Defensive',
            'industry': 'Household Products',
            'current_price': 155.20,
            'market_cap': 365000000000,
            'pe_ratio': 24.3,
            'dividend_yield': 0.0245,
            'beta': 0.42,
            '52_week_high': 165.35,
            '52_week_low': 138.52,
            'avg_volume': 6500000,
            'description': 'The Procter & Gamble Company provides branded consumer packaged goods to consumers worldwide...'
        },
        {
            'ticker': 'NVDA',
            'name': 'NVIDIA Corporation',
            'sector': 'Technology',
            'industry': 'Semiconductors',
            'current_price': 495.00,
            'market_cap': 1220000000000,
            'pe_ratio': 72.5,
            'dividend_yield': 0.0005,
            'beta': 1.75,
            '52_week_high': 502.66,
            '52_week_low': 108.13,
            'avg_volume': 48000000,
            'description': 'NVIDIA Corporation provides graphics, and compute and networking solutions worldwide...'
        },
        {
            'ticker': 'UNH',
            'name': 'UnitedHealth Group Incorporated',
            'sector': 'Healthcare',
            'industry': 'Healthcare Plans',
            'current_price': 522.00,
            'market_cap': 487000000000,
            'pe_ratio': 22.4,
            'dividend_yield': 0.0135,
            'beta': 0.73,
            '52_week_high': 558.10,
            '52_week_low': 445.68,
            'avg_volume': 3200000,
            'description': 'UnitedHealth Group Incorporated operates as a diversified health care company...'
        },
        {
            'ticker': 'HD',
            'name': 'The Home Depot, Inc.',
            'sector': 'Consumer Cyclical',
            'industry': 'Home Improvement',
            'current_price': 328.50,
            'market_cap': 330000000000,
            'pe_ratio': 21.2,
            'dividend_yield': 0.0255,
            'beta': 1.02,
            '52_week_high': 407.50,
            '52_week_low': 287.15,
            'avg_volume': 3800000,
            'description': 'The Home Depot, Inc. operates as a home improvement retailer...'
        },
        {
            'ticker': 'V',
            'name': 'Visa Inc.',
            'sector': 'Financial Services',
            'industry': 'Credit Services',
            'current_price': 268.00,
            'market_cap': 543000000000,
            'pe_ratio': 30.8,
            'dividend_yield': 0.0075,
            'beta': 1.05,
            '52_week_high': 282.36,
            '52_week_low': 217.65,
            'avg_volume': 7500000,
            'description': 'Visa Inc. operates as a payments technology company worldwide...'
        },
        {
            'ticker': 'GOOGL',
            'name': 'Alphabet Inc.',
            'sector': 'Technology',
            'industry': 'Internet Content',
            'current_price': 142.00,
            'market_cap': 1780000000000,
            'pe_ratio': 26.5,
            'dividend_yield': 0,
            'beta': 1.08,
            '52_week_high': 153.78,
            '52_week_low': 83.45,
            'avg_volume': 28000000,
            'description': 'Alphabet Inc. offers various products and platforms in the United States, Europe, and internationally...'
        },
        {
            'ticker': 'ABBV',
            'name': 'AbbVie Inc.',
            'sector': 'Healthcare',
            'industry': 'Drug Manufacturers',
            'current_price': 162.50,
            'market_cap': 287000000000,
            'pe_ratio': 38.2,
            'dividend_yield': 0.0375,
            'beta': 0.58,
            '52_week_high': 175.91,
            '52_week_low': 137.32,
            'avg_volume': 6800000,
            'description': 'AbbVie Inc. discovers, develops, manufactures, and sells pharmaceuticals worldwide...'
        },
        {
            'ticker': 'KO',
            'name': 'The Coca-Cola Company',
            'sector': 'Consumer Defensive',
            'industry': 'Beverages',
            'current_price': 58.50,
            'market_cap': 253000000000,
            'pe_ratio': 25.8,
            'dividend_yield': 0.0305,
            'beta': 0.58,
            '52_week_high': 64.99,
            '52_week_low': 51.55,
            'avg_volume': 16000000,
            'description': 'The Coca-Cola Company manufactures, markets, and sells various beverages worldwide...'
        },
        {
            'ticker': 'PEP',
            'name': 'PepsiCo, Inc.',
            'sector': 'Consumer Defensive',
            'industry': 'Beverages',
            'current_price': 168.00,
            'market_cap': 232000000000,
            'pe_ratio': 24.5,
            'dividend_yield': 0.0285,
            'beta': 0.63,
            '52_week_high': 186.84,
            '52_week_low': 158.48,
            'avg_volume': 4500000,
            'description': 'PepsiCo, Inc. manufactures, markets, distributes, and sells various beverages and foods worldwide...'
        },
        {
            'ticker': 'TSLA',
            'name': 'Tesla, Inc.',
            'sector': 'Consumer Cyclical',
            'industry': 'Auto Manufacturers',
            'current_price': 242.00,
            'market_cap': 768000000000,
            'pe_ratio': 68.5,
            'dividend_yield': 0,
            'beta': 2.05,
            '52_week_high': 299.29,
            '52_week_low': 101.81,
            'avg_volume': 125000000,
            'description': 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles and energy generation...'
        }
    ]
